import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { CaptureService, SqliteStore } from "@collector/api";
import type { ActiveModelRoute } from "@collector/capture-contracts";
import { FakeProvider, ModelGateway } from "@collector/model-gateway";

const route = (profileId: string, model: string): ActiveModelRoute => ({
  providerProfileId: profileId,
  providerId: profileId,
  apiMode: "openai_chat_completions",
  baseUrlFingerprint: profileId.repeat(64).slice(0, 64),
  model,
  configurationVersion: 1,
});

test("queued workflow keeps its provider route after the active provider changes", async (t) => {
  const root = await mkdtemp(join(tmpdir(), "collector-provider-route-"));
  const store = new SqliteStore(join(root, "collector.sqlite"));
  await store.init();
  t.after(async () => { store.close(); await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 }); });
  const service = new CaptureService(store, join(root, "artifacts"), undefined, undefined, { autoRunRecentOrganization: false });
  const first = await service.createCapture({ captureType: "pasted_text", content: "First routed material with enough content.", clientCaptureId: "route-1", capturedAt: new Date().toISOString() }, "route-1");
  const second = await service.createCapture({ captureType: "pasted_text", content: "Second routed material with enough content.", clientCaptureId: "route-2", capturedAt: new Date().toISOString() }, "route-2");
  const gatewayA = new ModelGateway(new FakeProvider([JSON.stringify({ clusters: [{ name: "Provider A", summary: "Generated by A.", materialIds: [first.id, second.id] }], unclusteredMaterialIds: [] })]), { model: "model-a" });
  const gatewayB = new ModelGateway(new FakeProvider([JSON.stringify({ clusters: [{ name: "Provider B", summary: "Generated by B.", materialIds: [first.id, second.id] }], unclusteredMaterialIds: [] })]), { model: "model-b" });
  const routeA = route("provider-a", "model-a");
  const routeB = route("provider-b", "model-b");
  service.setModelGateway(gatewayA, routeA);
  service.setModelGatewayResolver(async (frozen) => frozen.providerProfileId === routeA.providerProfileId ? gatewayA : gatewayB);
  const run = await service.organizeRecent("provider-route-run");
  assert.deepEqual(run.modelRoute, routeA);
  service.setModelGateway(gatewayB, routeB);
  await service.resumeRecentOrganizationRuns();
  assert.equal(service.getLatestRecentClusterSnapshot().clusters[0].name, "Provider A");
});
